=== tcm5343/HW4/StudentRegistration/StudentRegistration/Students.dtd
<!ELEMENT studentrecords (student*)>
<!ELEMENT student (FirstName, LastName, DegreeStatus, Major)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT DegreeStatus (#PCDATA)>
<!ELEMENT Major (#PCDATA)>

=== tcm5343/HW4/StudentRegistration/StudentRegistration/Students.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE studentrecords SYSTEM "Students.dtd">
<studentrecords>

<student>
<FirstName>Tom</FirstName>
<LastName>Miller</LastName>
<DegreeStatus>full-time</DegreeStatus>
<Major>IST</Major>
</student>

<student>
<FirstName>John</FirstName>
<LastName>Carlin</LastName>
<DegreeStatus>part-time</DegreeStatus>
<Major>IST</Major>
</student>

<student>
<FirstName>Ted</FirstName>
<LastName>White</LastName>
<DegreeStatus>non-degree</DegreeStatus>
<Major>HDFS</Major>
</student>

<student>
<FirstName>Skylar</FirstName>
<LastName>Anderson</LastName>
<DegreeStatus>provisional</DegreeStatus>
<Major>HDFS</Major>
</student>

<student>
<FirstName>Dr.</FirstName>
<LastName>Deb</LastName>
<DegreeStatus>part-time</DegreeStatus>
<Major>IST</Major>
</student>

<student>
<FirstName>Fred</FirstName>
<LastName>Aebli</LastName>
<DegreeStatus>provisional</DegreeStatus>
<Major>IST</Major>
</student>

<student>
<FirstName>Carls</FirstName>
<LastName>Junior</LastName>
<DegreeStatus>full-time</DegreeStatus>
<Major>Nursing</Major>
</student>

<student>
<FirstName>Nathan</FirstName>
<LastName>Freshman</LastName>
<DegreeStatus>full-time</DegreeStatus>
<Major>Business</Major>
</student>

</studentrecords>
